version: "3.8"
services:
  bingo-app:
    build: .
    container_name: "bingo-backend"
    ports:
      - 8080:8080
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27070:27017

volumes:
  mongodb_data: